// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ListAll"
                ],
                "summary": "List all tables",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/kurs": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CourseAction"
                ],
                "summary": "Rename course",
                "parameters": [
                    {
                        "description": "Rename course request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.RenameCourseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CourseAction"
                ],
                "summary": "Create course",
                "parameters": [
                    {
                        "description": "Create course request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CreateCourseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CourseAction"
                ],
                "summary": "Delete course",
                "parameters": [
                    {
                        "description": "Delete course request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DeleteCourseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            }
        },
        "/kurs/assign": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CourseAction"
                ],
                "summary": "Assign user to course",
                "parameters": [
                    {
                        "description": "Assign user request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.AssignUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            }
        },
        "/kurs/remove": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CourseAction"
                ],
                "summary": "Remove user from course",
                "parameters": [
                    {
                        "description": "Remove user request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.RemoveUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Registry"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login user",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Registry"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "Register user",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            }
        },
        "/specialtreatment/allstudents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SpecialTreatment"
                ],
                "summary": "Get all students",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.StudentInfo"
                            }
                        }
                    }
                }
            }
        },
        "/specialtreatment/creator": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SpecialTreatment"
                ],
                "summary": "Get courses created by a teacher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Teacher login (email)",
                        "name": "login",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Course"
                            }
                        }
                    }
                }
            }
        },
        "/specialtreatment/infotask": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SpecialTreatment"
                ],
                "summary": "Get info about a specific task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "zadanie_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Task"
                        }
                    }
                }
            }
        },
        "/specialtreatment/kursstudents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SpecialTreatment"
                ],
                "summary": "Get students enrolled in a specific course",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "kurs_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.StudentInfo"
                            }
                        }
                    }
                }
            }
        },
        "/specialtreatment/studentcourses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SpecialTreatment"
                ],
                "summary": "Get courses for a specific student by login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student login (email)",
                        "name": "login",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.StudentCourse"
                            }
                        }
                    }
                }
            }
        },
        "/specialtreatment/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SpecialTreatment"
                ],
                "summary": "Get tasks for a specific course",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "kurs_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Task"
                            }
                        }
                    }
                }
            }
        },
        "/whoami": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetInfo"
                ],
                "summary": "Who am I",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User login",
                        "name": "login",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            }
        },
        "/zadanie": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssignmentAction"
                ],
                "summary": "Reschedule assignment",
                "parameters": [
                    {
                        "description": "Reschedule assignment request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.RescheduleAssignmentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssignmentAction"
                ],
                "summary": "Create assignment",
                "parameters": [
                    {
                        "description": "Create assignment request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CreateAssignmentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssignmentAction"
                ],
                "summary": "Delete assignment",
                "parameters": [
                    {
                        "description": "Delete assignment request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DeleteAssignmentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            }
        },
        "/zadanie/check": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssignmentAction"
                ],
                "summary": "Check submission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student login",
                        "name": "student_login",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "kurs_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Assignment name",
                        "name": "nazwa_zadania",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            }
        },
        "/zadanie/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssignmentAction"
                ],
                "summary": "Submit assignment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student login",
                        "name": "student_login",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "kurs_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Assignment name",
                        "name": "nazwa_zadania",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Assignment file",
                        "name": "plik",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScriptResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.AssignUserReq": {
            "type": "object",
            "required": [
                "kurs_id",
                "student_login"
            ],
            "properties": {
                "kurs_id": {
                    "type": "integer"
                },
                "student_login": {
                    "type": "string"
                }
            }
        },
        "main.Course": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nazwa": {
                    "type": "string"
                }
            }
        },
        "main.CreateAssignmentReq": {
            "type": "object",
            "required": [
                "kurs_id",
                "nazwa_zadania",
                "opis",
                "termin"
            ],
            "properties": {
                "kurs_id": {
                    "type": "integer"
                },
                "nazwa_zadania": {
                    "type": "string"
                },
                "opis": {
                    "type": "string"
                },
                "termin": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                }
            }
        },
        "main.CreateCourseReq": {
            "type": "object",
            "required": [
                "nazwa",
                "wlasciciel_login"
            ],
            "properties": {
                "nazwa": {
                    "type": "string"
                },
                "wlasciciel_login": {
                    "type": "string"
                }
            }
        },
        "main.DeleteAssignmentReq": {
            "type": "object",
            "required": [
                "kurs_id",
                "nazwa_zadania"
            ],
            "properties": {
                "kurs_id": {
                    "type": "integer"
                },
                "nazwa_zadania": {
                    "type": "string"
                }
            }
        },
        "main.DeleteCourseReq": {
            "type": "object",
            "required": [
                "kurs_id"
            ],
            "properties": {
                "kurs_id": {
                    "type": "integer"
                }
            }
        },
        "main.LoginReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "main.RegisterReq": {
            "type": "object",
            "required": [
                "email",
                "imie",
                "nazwisko",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "imie": {
                    "type": "string"
                },
                "klasa": {
                    "type": "string"
                },
                "nazwisko": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "main.RemoveUserReq": {
            "type": "object",
            "required": [
                "kurs_id",
                "student_login"
            ],
            "properties": {
                "kurs_id": {
                    "type": "integer"
                },
                "student_login": {
                    "type": "string"
                }
            }
        },
        "main.RenameCourseReq": {
            "type": "object",
            "required": [
                "kurs_id",
                "nowa_nazwa"
            ],
            "properties": {
                "kurs_id": {
                    "type": "integer"
                },
                "nowa_nazwa": {
                    "type": "string"
                }
            }
        },
        "main.RescheduleAssignmentReq": {
            "type": "object",
            "required": [
                "kurs_id",
                "nazwa_zadania",
                "nowy_termin"
            ],
            "properties": {
                "kurs_id": {
                    "type": "integer"
                },
                "nazwa_zadania": {
                    "type": "string"
                },
                "nowy_termin": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                }
            }
        },
        "main.ScriptResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                }
            }
        },
        "main.StudentCourse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nazwa": {
                    "type": "string"
                },
                "wlasciciel": {
                    "type": "integer"
                }
            }
        },
        "main.StudentInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imie": {
                    "type": "string"
                },
                "klasa": {
                    "type": "string"
                },
                "nazwisko": {
                    "type": "string"
                }
            }
        },
        "main.Task": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kurs_id": {
                    "type": "integer"
                },
                "nazwa": {
                    "type": "string"
                },
                "opis": {
                    "type": "string"
                },
                "termin_realizacji": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your JWT token as: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Course System Backend",
	Description:      "API server for managing courses and assignments.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
